# Generated by Django 2.2.17 on 2021-01-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20210114_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
