# Generated by Django 2.2.17 on 2020-11-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='body_text',
            field=models.TextField(blank=True, verbose_name='Page content'),
        ),
        migrations.AlterField(
            model_name='page',
            name='update_date',
            field=models.DateTimeField(verbose_name='Last updated'),
        ),
    ]
